name: generated-code

on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Set up Go
      uses: actions/setup-go@v2.1.2
      with:
        go-version: 1.15
    - name: go run ./apispec-rule-gen
      working-directory: ./tools
      run: go run ./apispec-rule-gen && git diff --exit-code
